config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'bs_erb', to: 'pages#bs_erb'
  get 'bs_slim', to: 'pages#bs_slim'

  devise_scope :user do
    get 'profile/edit', to: 'devise/registrations#edit', as: :edit_user_registration
    get 'profile/cancel', to: 'devise/registrations#cancel', as: :cancel_user_registration
  end

  devise_for :users,  path: '',
                      path_names: { sign_in: 'login',
                                    sign_out: 'logout',
                                    sign_up: '',
                                    registration: 'signup',
                                    edit: 'profile',
                                    cancel: 'cancel',
                                    confirmation: 'verification' },
                      controllers: {  omniauth_callbacks: 'users/omniauth_callbacks',
                                      sessions: 'users/sessions',
                                      registrations: 'users/registrations' }

  resources :users, only: [:show]
  resources :rooms
  resources :photos

  resources :rooms do
    resources :bookings, only: [:create]
  end
  get '/preload', to: 'bookings#preload'

end

app/views/shared/_devise_messages.html.erb
<!-- - unless resource.errors.empty? -->
<% unless resource.errors.empty? %>
<!-- .callout.alert -->
<!-- = devise_error_messages! -->
<script type='text/javascript'>
  <% resource.errors.full_messages.each do |msg| %>
  toastr.error('<%= msg %>');
  <% end %>
</script>
<% end %>

app/views/shared/_flash.html.slim
- unless flash.empty?
  script[type='text/javascript']
    - flash.each do |f|
      - type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info')
        javascript:
	     	 toastr['#{type}']('#{f[1]}');

app/views/shared/_login.html.slim
#login-modal.small.reveal[data-reveal]
  .medium-10.medium-offset-1.large-6.large-offset-3.columns
    .center
      h2.text-center
        | Log in
      #login-modal-form
  button.close-button[data-close aria-label="Close modal" type="button"]
    span[aria-hidden="true"]
      | ×

app/views/shared/_navbar.html.slim
.title-bar[data-responsive-toggle="example-menu" data-hide-for="medium"]
  button.menu-icon[type="button" data-toggle="example-menu"]
  .title-bar-title
    | Menu
#example-menu.top-bar
  .container
    .row
      .top-bar-left
        ul.title-area
          li
            h4
              a href=(root_path) Airbnb clone
      .top-bar-left
        ul.dropdown.menu[data-dropdown-menu]
          li.menu-text
            | &nbsp;
          li
            input[type="search" placeholder="enter term here"]
          li
            button.airbnb.button[type="button"]
              | Search
          / li
          /   a[href="#"] First item
      .top-bar-right
        - if !user_signed_in?
          ul.menu
            li
              / a[data-open="login-modal" method: :get]
                / = "<i class='fa fa-sign-in'></i>Log in".html_safe
              = link_to "<i class='fa fa-sign-in'></i>Log in".html_safe, new_user_session_path, remote: true, method: :get, 'data-open': 'login-modal' 
            li
              / a[data-open="signupModal" method: :get]
              /   = "<i class='fa fa-user-plus'></i>Sign up".html_safe
              / = link_to "<i class='fa fa-user-plus'></i>Sign up".html_safe, new_user_registration_path
              = link_to "<i class='fa fa-user-plus'></i>Sign up".html_safe, new_user_registration_path, remote: true, method: :get, 'data-open': 'signup-modal' 
        - else
          ul.dropdown.menu[data-dropdown-menu]
            li
              = link_to "<i class='fa fa-home'></i>Create room".html_safe, new_room_path
            li
              = link_to "<i class='fa fa-list'></i>Room index".html_safe, rooms_path
            li
              a href=""
                = image_tag avatar_url(current_user), size: 20, class: 'img-circle'
                = current_user.full_name
              ul.menu.vertical
                li 
                  a[href="#"] Your trips
                li 
                  a[href="#"] Wish lists
                li
                  / = link_to '<i class="fi-torso size-18"></i>Edit Profile'.html_safe, edit_user_registration_path
                  = link_to "Edit profile", edit_user_registration_path
                li <hr>
                li 
                  a[href="#"] Account Settings
                li
                  = link_to "<i class='fa fa-sign-out'></i>Log out".html_safe, destroy_user_session_path, method: :delete, data: {confirm: 'Are you sure?'}
                / li
                /   button.alert.button[type="button"]
                /     a href=(root_path)
                /       <i class="fi-power size-18"></i>Log out
              / li 
                / | &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            li 
              = link_to "<i class='fa fa-envelope-o'></i>Messages".html_safe
            li
              = link_to "<i class='fa fa-home'></i>Become a host".html_safe

app/views/shared/_signup.html.slim
#signup-modal.small.reveal[data-reveal]
  .medium-10.medium-offset-1.large-6.large-offset-3.columns
    .center
      h2.text-center
        | Sign up
      #signup-modal-form
  button.close-button[data-close aria-label="Close modal" type="button"]
    span[aria-hidden="true"]
      | ×

app/views/shared/_toastr_flash.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |f| %>
      <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
      toastr['<%= type %>']('<%= f[1] %>', '', {"closeButton": true });
    <% end %>
  </script>
<% end %>