config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'bs_erb', to: 'pages#bs_erb'
  get 'bs_slim', to: 'pages#bs_slim'

  devise_scope :user do
    get 'profile/edit', to: 'devise/registrations#edit', as: :edit_user_registration
    get 'profile/cancel', to: 'devise/registrations#cancel', as: :cancel_user_registration
  end

  devise_for :users,  path: '',
                      path_names: { sign_in: 'login',
                                    sign_out: 'logout',
                                    sign_up: '',
                                    registration: 'signup',
                                    edit: 'profile',
                                    cancel: 'cancel',
                                    confirmation: 'verification' },
                      controllers: {  omniauth_callbacks: 'users/omniauth_callbacks',
                                      sessions: 'users/sessions',
                                      registrations: 'users/registrations' }

  resources :users, only: [:show]
  resources :rooms
  resources :photos

  resources :rooms do
    resources :bookings, only: [:create]
  end
  get '/preload', to: 'bookings#preload'

end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :photos, dependent: :destroy
  has_many :bookings

  geocoded_by :address
  after_validation :geocode, if: :address_changed? # auto-fetch coordinates

  validates :home_type, presence: true
  validates :room_type, presence: true
  validates :accomodate, presence: true
  validates :bedroom, presence: true
  validates :bathroom, presence: true
  validates :listing_name, presence: true, length: { maximum: 50 }
  validates :summary, presence: true, length: { maximum: 500 }
  validates :address, presence: true
  validates :price, presence: true
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update]
  before_action :authenticate_user!, except: [:show]

  def index
    @rooms = current_user.rooms.all
  end

  def show
    @photos = @room.photos
  end

  def new
    @room = current_user.rooms.build
  end

  def create
    @room = current_user.rooms.build(room_params)

    if @room.save
      if params[:images]
        params[:images].each do |image|
          @room.photos.create(image: image)
        end
      end
      @photos = @room.photos
      redirect_to room_path(@room), flash: { success: 'Created room' }
    else
      flash[:alert] = @room.errors.full_messages.first
      render :new
    end
  end

  def edit
    if current_user.id == @room.user.id
      @photos = @room.photos
    else
      redirect_to root_path, flash: { alert: "You don't have permission" }
    end
  end

  def update
    if @room.update(room_params)
      if params[:images]
        params[:images].each do |image|
          @room.photos.create(image: image)
        end
      end
      redirect_to edit_room_path(@room), flash: { success: 'Updated room' }
    else
      flash[:alert] = @room.errors.full_messages.first
      render :edit
    end
  end

  def destroy; end

  private

  def set_room
    @room = Room.find(params[:id])
  end

  def room_params
    params.require(:room).permit(:home_type,
                                 :room_type,
                                 :accomodate,
                                 :bedroom,
                                 :bathroom,
                                 :listing_name,
                                 :summary,
                                 :address,
                                 :is_tv,
                                 :is_kitchen,
                                 :is_air,
                                 :is_heating,
                                 :is_internet,
                                 :price,
                                 :active)
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.slim
.card
  .card-divider
    h3.text-center 
      | Create your listing
  .card-section
    = form_for @room, html: {multipart: true} do |f|
      .row
        .medium-8.medium-centered.columns
          .row
            .field
              .medium-4.columns
                = f.label :home_type
                = f.select :home_type, [["Apartment", "Apartment"], 
                                        ["House", "House"], 
                                        ["Bed & Breakfast", 'Bed & Breakfast']],
                                        id: 'home_type', prompt: "Select...", autofocus: true
            .field
              .medium-4.columns
                = f.label :room_type
                = f.select :room_type, [["Entire Home", "Entire Home"], 
                                        ["Private Room", "Private Room"], 
                                        ["Shared Room", 'Shared Room']],
                                        id: 'room_type', prompt: "Select...", autofocus: true
            .field
              .medium-4.columns
                = f.label :accomodates
                = f.select :accomodate, [["1 person", 1], 
                                        ["2 people", 2], 
                                        ["3 people", 3],
                                        ["4 people", 4],
                                        ["5 people", 5], 
                                        ["6 people", 6],],
                                        id: 'accomodate', prompt: "Select...", autofocus: true
          .row
            .field
              .medium-4.columns
                = f.label :price_per_night
                .input-group
                  span.input-group-label
                    | $
                  = f.number_field :price, class: 'input-group-field', min: "1"
            .field
              .medium-4.columns
                = f.label :bedrooms
                = f.select :bedroom, [["1", 1], 
                                        ["2", 2], 
                                        ["3", 3],
                                        ["4", 4],
                                        ["5", 5], 
                                        ["6", 6],],
                                        id: 'bedroom', prompt: "Select...", autofocus: true
            .field
              .medium-4.columns
                = f.label :bathrooms
                = f.select :bathroom, [["1", 1], 
                                        ["2", 2], 
                                        ["3", 3],
                                        ["4", 4],
                                        ["5", 5], 
                                        ["6", 6],],
                                        id: 'bathroom', prompt: "Select...", autofocus: true
          .row 
            .field
              .medium-12.columns
                = f.label :listing_name
                = f.text_field :listing_name, placeholder: 'Be clear and descriptive', autofocus: true
          .row
            .field
              .medium-12.columns
                = f.label :summary
                = f.text_area :summary, rows: 3, placeholder: 'Tell us about your place', autofocus: true
          .row
            .field
              .medium-12.columns
                = f.label :address
                = f.text_field :address, placeholder: 'What is your address', autofocus: true                                 
          .row
            .field
              .medium-4.small-6.columns
                = f.check_box :is_internet
                = f.label :internet
            .field
              .medium-4.small-6.columns
                = f.check_box :is_tv
                = f.label :tv, class: 'uppercase'
            .field
              .medium-4.small-6.columns
                = f.check_box :is_kitchen
                = f.label :kitchen
          .row
            .field
              .medium-4.small-6.columns
                = f.check_box :is_air
                = f.label :airconditioning
            .field
              .medium-4.small-6.columns.end
                = f.check_box :is_heating
                = f.label :heating
            .field
              .medium-4.columns
                = f.check_box :active
                = f.label :active_listing
          br
          .row
            .field
              .medium-4.columns
                a.alert.hollow.button.button-file
                  i.fa.fa-cloud-upload
                  |  Upload photos
                  = file_field_tag "images[]", type: :file, multiple: true
          #photos
            = render 'photos/list'
          br
          .actions
            = f.submit "Save", class: 'airbnb button float-center'
            / = link_to "Back", :back, class: "button float-right"
          
                  

app/views/rooms/_google_map.html.erb
<div id="map"></div>

<style>
  #map {
    height: 400px;
    width: 100%;
  }

</style>

<script>
  function initMap() {
    var myLatlng = {
      lat: <%= @room.latitude %>,
      lng: <%= @room.longitude %>
    };
    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 15,
      center: myLatlng
    });
    var title = '<%= @room.listing_name %>'
    var marker = new google.maps.Marker({
      position: myLatlng,
      map: map,
      title: title,
      label: {
        fontFamily: 'Fontawesome',
        text: '\uf015'
      },
      animation: google.maps.Animation.DROP
    });
    marker.setMap(map);
  }
</script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['GOOGLE_MAPS_API_KEY']%>&callback=initMap"></script>

app/views/rooms/edit.html.slim
= render 'form'

app/views/rooms/index.html.slim
.medium-3.columns
  ul.sidebar-list.no-bullet
    li.sidebar-item
      = link_to 'Your Listings', rooms_path, class: 'sidebar-link active'
    li.sidebar-item
      = link_to 'Your Reservations'
.medium-9.columns
  .card
    .card-divider
      h3 Listings
    .card-section
      - @rooms.each do |room|
        .row
          .medium-2.columns
            = link_to room_path(room)
              = image_tag image_url(room.photos.first), class: 'thumb' 
            / - if room.photos.present?
            /   = image_tag room.photos.first.image.url(:thumb)
            / - else 
            /   = image_tag 'image-coming-soon.png'
          .medium-7.columns
            h4 
              = link_to room.listing_name, room_path(room)
            p 
              = truncate(room.summary, length: 80)
          .medium-3.columns
            = link_to 'Edit', edit_room_path(room), class: 'airbnb button'
        hr

app/views/rooms/new.html.slim
= render 'form'

app/views/rooms/show.html.slim
.card
  .card-divider
    h3.text-center
      = @room.listing_name
  .card-section
    .medium-10.medium-centered.columns
      // Image
      .row
        .medium-12.columns
          - if @photos.present?
            .orbit[role="region" aria-label="listing photos" data-orbit]
              ul.orbit-container
                button.orbit-previous
                  span.show-for-sr
                    | Previous Slide
                  i.fa.fa-angle-left
                button.orbit-next
                  span.show-for-sr
                    | Next Slide
                  i.fa.fa-angle-right
                - @photos.each do |photo|
                  li.is-active.orbit-slide
                    = image_tag photo.image.url, alt: "#{photo.image_file_name}", class: 'float-center medium orbit-image'
                    / figcaption.orbit-caption
                    /   | Space, the final frontier.
              nav.orbit-bullets
                - @photos.each do |photo|
                  button
                  / button class=('is-active' if photo.id == @photos[0].id)
                    span.show-for-sr
                      | First slide details
          - else
            = image_tag image_url(@room.photos.first), class: 'medium float-center'
      // Main info
      .row
        .medium-8.columns
          .row
            .medium-3.columns.text-center
              = link_to user_path(@room.user)
                = image_tag avatar_url(@room.user) + "?type=large", class: 'img-circle'
              br
              = link_to user_path(@room.user)
                = @room.user.full_name
            .medium-9.columns
              h3
                = @room.listing_name
              = @room.address
              .row.row-space-6.text-center
                .small-3.columns
                  i.fa.fa-home.fa-2x
                  br
                  = @room.home_type
                .small-3.columns
                  i.fa.fa-users.fa-2x
                  br
                  = pluralize(@room.accomodate, "guest")
                .small-3.columns
                  i.fa.fa-bed.fa-2x
                  br
                  = pluralize(@room.bedroom, "bedroom")
                .small-3.columns
                  i.fa.fa-bath.fa-2x
                  br
                  = pluralize(@room.bathroom, "bathroom")
        .medium-4.columns
          // Reservation form
          = render 'bookings/form'
      .row
        // About
        .medium-7.columns
          h3 About this room
          p
            = @room.summary
        // Ammenities
        .medium-4.medium-offset-1.columns
          h3 Amenities
          ul.amenities.no-bullet
            li class=(@room.is_internet? ? '' : 'line-through')
              - if @room.is_internet?
                i.fa.fa-check-circle.fa-lg &nbsp;&nbsp; 
              - else 
                i.fa.fa-times.fa-lg &nbsp;&nbsp;
              | Internet
            li class=(@room.is_tv? ? '' : 'line-through')
              - if @room.is_tv?
                i.fa.fa-check-circle.fa-lg &nbsp;&nbsp; 
              - else 
                i.fa.fa-times.fa-lg &nbsp;&nbsp;
              | TV
            li class=(@room.is_kitchen? ? '' : 'line-through')
              - if @room.is_kitchen?
                i.fa.fa-check-circle.fa-lg &nbsp;&nbsp; 
              - else 
                i.fa.fa-times.fa-lg &nbsp;&nbsp;
              | Kitchen
            li class=(@room.is_air? ? '' : 'line-through')
              - if @room.is_air?
                i.fa.fa-check-circle.fa-lg &nbsp;&nbsp; 
              - else 
                i.fa.fa-times.fa-lg &nbsp;&nbsp;
              | Airconditioning
            li class=(@room.is_heating? ? '' : 'line-through')
              - if @room.is_heating?
                i.fa.fa-check-circle.fa-lg &nbsp;&nbsp; 
              - else 
                i.fa.fa-times.fa-lg &nbsp;&nbsp;
              | Heating
      // Google maps
      .row
        .medium-12.columns
          h3 Location
          = render 'rooms/google_map'
      br
      // Nearby rooms
      .row
        .medium-12.columns
          h3
            | Nearby rooms
      .row.medium-up-3[data-equalizer data-equalize-on="medium"]
        - @room.nearbys(10).first(3).each do |room|
          .column.column-block
            .card.photo-card[data-equalizer-watch]
              .room-photo
                = link_to room_path(room)
                  = image_tag image_url(room.photos.first), class: 'medium float-center'
              .card-divider.text-center
                = link_to room.listing_name, room_path(room)
                br
                | $
                = room.price
                | &nbsp;
                | /&nbsp;per&nbsp;night
                | &nbsp;&nbsp;(
                = room.distance.round(2)
                |  miles away)
                